# Don't print a line at the start of the prompt
[character]
symbol = "⮞"

[username]
show_always = true
style_user ="#3daee9"

[hostname]
ssh_only = false
disabled = false
style = "bold white"

[directory]
style = "#4DFFB2"

[rust]
disabled = false

[python]
disabled = true

[ruby]
disabled = true

[golang]
disabled = true

[nodejs]
disabled = false

[package]
disabled =true 
display_private = true
